"""Phase 0 initial schema.

Written as raw SQL rather than op.create_table() because it contains
extensions, views and triggers that Alembic autogenerate cannot express.
Later migrations should be autogenerated against app.models.

Revision ID: 0001
Revises:
"""

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


SCHEMA = r"""
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "vector";

-- ---------------------------------------------------------------------------
-- Identity
-- ---------------------------------------------------------------------------

CREATE TYPE user_role AS ENUM ('student', 'instructor', 'researcher', 'admin');

CREATE TABLE users (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email          text NOT NULL,
    email_lower    text GENERATED ALWAYS AS (lower(email)) STORED,
    password_hash  text NOT NULL,
    display_name   text NOT NULL,
    role           user_role NOT NULL DEFAULT 'student',
    is_active      boolean NOT NULL DEFAULT true,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX users_email_lower_key ON users (email_lower);

CREATE TABLE refresh_tokens (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  text NOT NULL UNIQUE,
    issued_at   timestamptz NOT NULL DEFAULT now(),
    expires_at  timestamptz NOT NULL,
    revoked_at  timestamptz
);
CREATE INDEX refresh_tokens_user_idx ON refresh_tokens (user_id) WHERE revoked_at IS NULL;

-- ---------------------------------------------------------------------------
-- Courses and source material
-- ---------------------------------------------------------------------------

CREATE TABLE courses (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id    uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    slug        text NOT NULL UNIQUE,
    title       text NOT NULL,
    description text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE enrollments (
    course_id   uuid NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    user_id     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    enrolled_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (course_id, user_id)
);

CREATE TYPE document_status AS ENUM ('uploaded', 'chunked', 'embedded', 'failed');

CREATE TABLE source_documents (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    course_id    uuid NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    title        text NOT NULL,
    storage_key  text NOT NULL,            -- R2 object key
    mime_type    text NOT NULL,
    sha256       text NOT NULL,
    page_count   integer,
    status       document_status NOT NULL DEFAULT 'uploaded',
    uploaded_by  uuid REFERENCES users(id) ON DELETE SET NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (course_id, sha256)
);

-- Every grounded claim the system makes must point at one of these rows.
CREATE TABLE source_chunks (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id uuid NOT NULL REFERENCES source_documents(id) ON DELETE CASCADE,
    ordinal     integer NOT NULL,
    text        text NOT NULL,
    page_from   integer,
    page_to     integer,
    token_count integer,
    embedding   vector(1536),
    created_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (document_id, ordinal)
);
CREATE INDEX source_chunks_document_idx ON source_chunks (document_id);

-- ---------------------------------------------------------------------------
-- Concept model
-- ---------------------------------------------------------------------------

CREATE TABLE concepts (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    course_id      uuid NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    slug           text NOT NULL,
    canonical_name text NOT NULL,
    description    text,
    -- set when a duplicate is merged into a canonical concept
    merged_into_id uuid REFERENCES concepts(id) ON DELETE SET NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (course_id, slug)
);
CREATE INDEX concepts_active_idx ON concepts (course_id) WHERE merged_into_id IS NULL;

CREATE TYPE concept_relation AS ENUM ('prerequisite_of', 'part_of', 'related_to');

CREATE TABLE concept_edges (
    from_concept_id uuid NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
    to_concept_id   uuid NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
    relation        concept_relation NOT NULL,
    weight          real NOT NULL DEFAULT 1.0 CHECK (weight >= 0 AND weight <= 1),
    created_at      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (from_concept_id, to_concept_id, relation),
    CHECK (from_concept_id <> to_concept_id)
);

CREATE TABLE concept_evidence (
    concept_id uuid NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
    chunk_id   uuid NOT NULL REFERENCES source_chunks(id) ON DELETE CASCADE,
    note       text,
    PRIMARY KEY (concept_id, chunk_id)
);

CREATE TABLE misconceptions (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    concept_id     uuid NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
    slug           text NOT NULL,
    name           text NOT NULL,
    -- the incorrect mental model, stated as the learner would hold it
    incorrect_model text NOT NULL,
    typical_signals text,
    created_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (concept_id, slug)
);

-- ---------------------------------------------------------------------------
-- AI provenance. Every model call writes exactly one row here, and every
-- artefact derived from a model call references it.
-- ---------------------------------------------------------------------------

CREATE TABLE ai_runs (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    purpose        text NOT NULL,   -- concept_extraction | question_generation | ...
    provider       text NOT NULL,
    model          text NOT NULL,
    prompt_name    text NOT NULL,
    prompt_version text NOT NULL,
    prompt_sha256  text NOT NULL,
    input_sha256   text NOT NULL,
    params         jsonb NOT NULL DEFAULT '{}'::jsonb,  -- temperature, seed, top_p
    raw_output     jsonb,
    ok             boolean NOT NULL DEFAULT true,
    error          text,
    tokens_in      integer,
    tokens_out     integer,
    latency_ms     integer,
    cost_usd       numeric(10, 6),
    request_id     text,
    created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ai_runs_purpose_created_idx ON ai_runs (purpose, created_at DESC);
CREATE INDEX ai_runs_request_idx ON ai_runs (request_id);

-- ---------------------------------------------------------------------------
-- Questions
-- ---------------------------------------------------------------------------

CREATE TYPE question_type AS ENUM ('mcq', 'short_answer', 'numeric', 'explanation', 'diagram');
CREATE TYPE question_status AS ENUM ('draft', 'validated', 'needs_repair', 'invalid', 'retired');

CREATE TABLE questions (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    course_id           uuid NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    type                question_type NOT NULL,
    stem                text NOT NULL,
    options             jsonb,          -- [{id, text, is_correct, distractor_rationale}]
    correct_answer      text,
    answer_rationale    text,
    difficulty          real CHECK (difficulty >= 0 AND difficulty <= 1),
    bloom_level         text,
    status              question_status NOT NULL DEFAULT 'draft',
    -- Fixed pre/post-test items. Never enters the adaptive pool.
    is_fixed_instrument boolean NOT NULL DEFAULT false,
    authored_by         uuid REFERENCES users(id) ON DELETE SET NULL,
    ai_run_id           uuid REFERENCES ai_runs(id) ON DELETE SET NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CHECK (type <> 'mcq' OR options IS NOT NULL)
);
CREATE INDEX questions_course_status_idx ON questions (course_id, status);

CREATE TABLE question_concepts (
    question_id uuid NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    concept_id  uuid NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
    weight      real NOT NULL DEFAULT 1.0 CHECK (weight > 0 AND weight <= 1),
    is_primary  boolean NOT NULL DEFAULT false,
    PRIMARY KEY (question_id, concept_id)
);

CREATE TABLE question_evidence (
    question_id uuid NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    chunk_id    uuid NOT NULL REFERENCES source_chunks(id) ON DELETE CASCADE,
    quote       text,
    PRIMARY KEY (question_id, chunk_id)
);

CREATE TYPE validation_verdict AS ENUM ('pass', 'repair_suggested', 'fail');

CREATE TABLE question_validations (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    question_id uuid NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    verdict     validation_verdict NOT NULL,
    confidence  real CHECK (confidence >= 0 AND confidence <= 1),
    checks      jsonb NOT NULL DEFAULT '{}'::jsonb,  -- per-criterion results
    issues      jsonb NOT NULL DEFAULT '[]'::jsonb,
    reviewer_id uuid REFERENCES users(id) ON DELETE SET NULL,  -- human review
    ai_run_id   uuid REFERENCES ai_runs(id) ON DELETE SET NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX question_validations_question_idx ON question_validations (question_id, created_at DESC);

-- The only pool the adaptive engine may draw from.
-- Columns are listed rather than SELECT *: Postgres freezes a view's column
-- list at creation, so a later ALTER TABLE would silently not appear here.
CREATE VIEW adaptive_question_pool AS
SELECT q.id,
       q.course_id,
       q.type,
       q.stem,
       q.options,
       q.difficulty,
       q.bloom_level,
       q.status,
       q.is_fixed_instrument,
       q.created_at
FROM questions q
WHERE q.status = 'validated'
  AND q.is_fixed_instrument = false;

-- ---------------------------------------------------------------------------
-- Fixed instruments (pre-test / post-test). Immutable once locked.
-- ---------------------------------------------------------------------------

CREATE TYPE instrument_kind AS ENUM ('pretest', 'posttest', 'practice');

CREATE TABLE assessment_instruments (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    course_id  uuid NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    kind       instrument_kind NOT NULL,
    version    integer NOT NULL DEFAULT 1,
    title      text NOT NULL,
    locked_at  timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (course_id, kind, version)
);

CREATE TABLE instrument_items (
    instrument_id uuid NOT NULL REFERENCES assessment_instruments(id) ON DELETE CASCADE,
    question_id   uuid NOT NULL REFERENCES questions(id) ON DELETE RESTRICT,
    position      integer NOT NULL,
    PRIMARY KEY (instrument_id, question_id),
    UNIQUE (instrument_id, position)
);

-- Guard 1: instrument items must be flagged as fixed, so they can never
-- leak into adaptive_question_pool.
CREATE FUNCTION enforce_fixed_instrument_item() RETURNS trigger AS $$
BEGIN
    IF NOT (SELECT is_fixed_instrument FROM questions WHERE id = NEW.question_id) THEN
        RAISE EXCEPTION
            'question % is not flagged is_fixed_instrument and cannot join an instrument',
            NEW.question_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER instrument_items_fixed_only
    BEFORE INSERT OR UPDATE ON instrument_items
    FOR EACH ROW EXECUTE FUNCTION enforce_fixed_instrument_item();

-- Guard 2: a locked instrument cannot change. This is the schema-level
-- expression of "pre/post-test must stay independent of the intervention".
CREATE FUNCTION enforce_instrument_lock() RETURNS trigger AS $$
DECLARE
    target uuid := COALESCE(NEW.instrument_id, OLD.instrument_id);
BEGIN
    IF (SELECT locked_at FROM assessment_instruments WHERE id = target) IS NOT NULL THEN
        RAISE EXCEPTION 'instrument % is locked and its items cannot be changed', target;
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER instrument_items_locked
    BEFORE INSERT OR UPDATE OR DELETE ON instrument_items
    FOR EACH ROW EXECUTE FUNCTION enforce_instrument_lock();

-- Guard 3: a question used by any instrument cannot have its stem, options
-- or correct answer edited.
CREATE FUNCTION enforce_locked_question_immutable() RETURNS trigger AS $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM instrument_items ii
        JOIN assessment_instruments ai ON ai.id = ii.instrument_id
        WHERE ii.question_id = NEW.id AND ai.locked_at IS NOT NULL
    ) AND (
        NEW.stem IS DISTINCT FROM OLD.stem
        OR NEW.options IS DISTINCT FROM OLD.options
        OR NEW.correct_answer IS DISTINCT FROM OLD.correct_answer
    ) THEN
        RAISE EXCEPTION 'question % belongs to a locked instrument and is immutable', NEW.id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER questions_locked_immutable
    BEFORE UPDATE ON questions
    FOR EACH ROW EXECUTE FUNCTION enforce_locked_question_immutable();

-- ---------------------------------------------------------------------------
-- Sessions, attempts, analyses
-- ---------------------------------------------------------------------------

CREATE TYPE session_mode AS ENUM ('adaptive', 'control', 'fixed_instrument', 'practice');

CREATE TABLE sessions (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    course_id     uuid NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    mode          session_mode NOT NULL,
    instrument_id uuid REFERENCES assessment_instruments(id) ON DELETE RESTRICT,
    started_at    timestamptz NOT NULL DEFAULT now(),
    ended_at      timestamptz,
    CHECK ((mode = 'fixed_instrument') = (instrument_id IS NOT NULL))
);
CREATE INDEX sessions_user_idx ON sessions (user_id, started_at DESC);

CREATE TABLE attempts (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id        uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    user_id           uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    question_id       uuid NOT NULL REFERENCES questions(id) ON DELETE RESTRICT,
    attempt_no        integer NOT NULL DEFAULT 1,
    response_text     text,
    response_modality text NOT NULL DEFAULT 'text',  -- text | image | handwriting | diagram
    response_media_key text,                          -- R2 key when non-text
    served_at         timestamptz NOT NULL DEFAULT now(),
    submitted_at      timestamptz,
    latency_ms        integer,
    hints_used        integer NOT NULL DEFAULT 0,
    is_correct        boolean,
    score             real CHECK (score >= 0 AND score <= 1),
    created_at        timestamptz NOT NULL DEFAULT now(),
    UNIQUE (session_id, question_id, attempt_no)
);
CREATE INDEX attempts_user_question_idx ON attempts (user_id, question_id);

CREATE TYPE diagnosis_kind AS ENUM (
    'correct_with_sound_reasoning',
    'correct_reasoning_unclear',
    'procedural_slip',
    'knowledge_gap',
    'misconception',
    'insufficient_evidence'
);

CREATE TABLE attempt_analyses (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    attempt_id     uuid NOT NULL UNIQUE REFERENCES attempts(id) ON DELETE CASCADE,
    diagnosis      diagnosis_kind NOT NULL,
    confidence     real NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    -- what was actually observed, kept separate from what was inferred
    observations   jsonb NOT NULL DEFAULT '[]'::jsonb,
    inference      text,
    alternatives   jsonb NOT NULL DEFAULT '[]'::jsonb,
    misconception_id uuid REFERENCES misconceptions(id) ON DELETE SET NULL,
    ai_run_id      uuid REFERENCES ai_runs(id) ON DELETE SET NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    CHECK (diagnosis <> 'misconception' OR misconception_id IS NOT NULL)
);

-- ---------------------------------------------------------------------------
-- Learner model. Current state is mutable; history is append-only.
-- ---------------------------------------------------------------------------

CREATE TABLE learner_states (
    user_id          uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    concept_id       uuid NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
    mastery_mean     real NOT NULL DEFAULT 0.5 CHECK (mastery_mean >= 0 AND mastery_mean <= 1),
    mastery_variance real NOT NULL DEFAULT 0.08 CHECK (mastery_variance >= 0),
    observations     integer NOT NULL DEFAULT 0,
    last_attempt_id  uuid REFERENCES attempts(id) ON DELETE SET NULL,
    updated_at       timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, concept_id)
);

CREATE TABLE learner_state_history (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    concept_id       uuid NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
    attempt_id       uuid REFERENCES attempts(id) ON DELETE SET NULL,
    mastery_mean     real NOT NULL,
    mastery_variance real NOT NULL,
    observations     integer NOT NULL,
    update_reason    text NOT NULL,
    model_version    text NOT NULL,
    recorded_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX learner_state_history_user_concept_idx
    ON learner_state_history (user_id, concept_id, recorded_at DESC);

CREATE TABLE learner_misconception_states (
    user_id          uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    misconception_id uuid NOT NULL REFERENCES misconceptions(id) ON DELETE CASCADE,
    belief           real NOT NULL DEFAULT 0 CHECK (belief >= 0 AND belief <= 1),
    supporting_count integer NOT NULL DEFAULT 0,
    refuting_count   integer NOT NULL DEFAULT 0,
    first_seen_at    timestamptz NOT NULL DEFAULT now(),
    last_seen_at     timestamptz NOT NULL DEFAULT now(),
    resolved_at      timestamptz,
    PRIMARY KEY (user_id, misconception_id)
);

-- ---------------------------------------------------------------------------
-- Adaptive decisions. One row per selection, enough to replay it.
-- ---------------------------------------------------------------------------

CREATE TABLE selection_decisions (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id         uuid NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    chosen_question_id uuid REFERENCES questions(id) ON DELETE SET NULL,
    policy_name        text NOT NULL,
    policy_version     text NOT NULL,
    rng_seed           bigint NOT NULL,
    learner_snapshot   jsonb NOT NULL,   -- state read at decision time
    candidates         jsonb NOT NULL,   -- [{question_id, score, components}]
    rationale          text,
    decided_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX selection_decisions_session_idx ON selection_decisions (session_id, decided_at);

-- ---------------------------------------------------------------------------
-- Interaction log. Append-only.
-- ---------------------------------------------------------------------------

CREATE TABLE interactions (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     uuid REFERENCES users(id) ON DELETE SET NULL,
    session_id  uuid REFERENCES sessions(id) ON DELETE SET NULL,
    event_type  text NOT NULL,
    payload     jsonb NOT NULL DEFAULT '{}'::jsonb,
    request_id  text,
    occurred_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX interactions_session_idx ON interactions (session_id, occurred_at);
CREATE INDEX interactions_type_idx ON interactions (event_type, occurred_at DESC);

CREATE FUNCTION reject_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'table % is append-only', TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER interactions_append_only
    BEFORE UPDATE OR DELETE ON interactions
    FOR EACH STATEMENT EXECUTE FUNCTION reject_mutation();

CREATE TRIGGER learner_state_history_append_only
    BEFORE UPDATE OR DELETE ON learner_state_history
    FOR EACH STATEMENT EXECUTE FUNCTION reject_mutation();

CREATE TRIGGER ai_runs_append_only
    BEFORE UPDATE OR DELETE ON ai_runs
    FOR EACH STATEMENT EXECUTE FUNCTION reject_mutation();

CREATE TRIGGER selection_decisions_append_only
    BEFORE UPDATE OR DELETE ON selection_decisions
    FOR EACH STATEMENT EXECUTE FUNCTION reject_mutation();

-- ---------------------------------------------------------------------------
-- Research
-- ---------------------------------------------------------------------------

CREATE TYPE study_condition AS ENUM ('adaptive', 'control');

CREATE TABLE studies (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    course_id  uuid NOT NULL REFERENCES courses(id) ON DELETE RESTRICT,
    name       text NOT NULL,
    protocol_version text NOT NULL,
    ethics_ref text,
    opened_at  timestamptz,
    closed_at  timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE study_participants (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    study_id         uuid NOT NULL REFERENCES studies(id) ON DELETE RESTRICT,
    user_id          uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    pseudonym        text NOT NULL UNIQUE,
    condition        study_condition NOT NULL,
    consent_version  text NOT NULL,
    consented_at     timestamptz NOT NULL,
    enrolled_at      timestamptz NOT NULL DEFAULT now(),
    withdrawn_at     timestamptz,
    UNIQUE (study_id, user_id)
);

-- Condition is assigned once at enrolment and never recomputed.
CREATE FUNCTION freeze_condition() RETURNS trigger AS $$
BEGIN
    IF NEW.condition IS DISTINCT FROM OLD.condition THEN
        RAISE EXCEPTION 'study condition for participant % is frozen at enrolment', OLD.id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER study_participants_condition_frozen
    BEFORE UPDATE ON study_participants
    FOR EACH ROW EXECUTE FUNCTION freeze_condition();
"""


DROP = r"""
DROP TABLE IF EXISTS study_participants CASCADE;
DROP TABLE IF EXISTS studies CASCADE;
DROP TABLE IF EXISTS interactions CASCADE;
DROP TABLE IF EXISTS selection_decisions CASCADE;
DROP TABLE IF EXISTS learner_misconception_states CASCADE;
DROP TABLE IF EXISTS learner_state_history CASCADE;
DROP TABLE IF EXISTS learner_states CASCADE;
DROP TABLE IF EXISTS attempt_analyses CASCADE;
DROP TABLE IF EXISTS attempts CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS instrument_items CASCADE;
DROP TABLE IF EXISTS assessment_instruments CASCADE;
DROP VIEW  IF EXISTS adaptive_question_pool CASCADE;
DROP TABLE IF EXISTS question_validations CASCADE;
DROP TABLE IF EXISTS question_evidence CASCADE;
DROP TABLE IF EXISTS question_concepts CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS ai_runs CASCADE;
DROP TABLE IF EXISTS misconceptions CASCADE;
DROP TABLE IF EXISTS concept_evidence CASCADE;
DROP TABLE IF EXISTS concept_edges CASCADE;
DROP TABLE IF EXISTS concepts CASCADE;
DROP TABLE IF EXISTS source_chunks CASCADE;
DROP TABLE IF EXISTS source_documents CASCADE;
DROP TABLE IF EXISTS enrollments CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP FUNCTION IF EXISTS reject_mutation CASCADE;
DROP FUNCTION IF EXISTS freeze_condition CASCADE;
DROP FUNCTION IF EXISTS enforce_instrument_lock CASCADE;
DROP FUNCTION IF EXISTS enforce_fixed_instrument_item CASCADE;
DROP FUNCTION IF EXISTS enforce_locked_question_immutable CASCADE;

DROP TYPE IF EXISTS study_condition CASCADE;
DROP TYPE IF EXISTS diagnosis_kind CASCADE;
DROP TYPE IF EXISTS session_mode CASCADE;
DROP TYPE IF EXISTS instrument_kind CASCADE;
DROP TYPE IF EXISTS validation_verdict CASCADE;
DROP TYPE IF EXISTS question_status CASCADE;
DROP TYPE IF EXISTS question_type CASCADE;
DROP TYPE IF EXISTS concept_relation CASCADE;
DROP TYPE IF EXISTS document_status CASCADE;
DROP TYPE IF EXISTS user_role CASCADE;
"""


def upgrade() -> None:
    op.execute(SCHEMA)


def downgrade() -> None:
    op.execute(DROP)
